# This is a basic workflow to help you get started with Actions
name: k6 Load Test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  loadtest:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run k6
        uses: grafana/k6-action@v0.3.1
        with:
          filename: script.js

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: result.html
